id: P006639
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1137
  title: བླ་མ་མཆོད་པའི་ཆོ་ག་དངོས་གྲུབ་རིན་པོ་ཆེའི་གཏེར་མཛོད
  author: ''
  volumes:
    fa2f4a06ec944ad286b9515f74d1307e:
      image_group_id: I1CZ1534
      title: ''
      volume_number: 1
      total_pages: 24
